import './globals.css'
import Header from './components/Header';
import { Roboto,Arimo } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from './components/Footer';

const arimo = Arimo({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable:"--primary-font",
})
 
const roboto = Roboto({
  weight: ['300','400','500'],
  subsets: ['latin'],
  display: 'swap',
  variable:"--secondary-font",

})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${arimo.variable} ${roboto.variable}`}>
    <body>
    <Header/>
    {children}
    <Footer/>
    </body>
  </html>
  )
}
